# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
PATH=/its1/GB_BT2/jianzuoyi/biosoft/anaconda/bin:$PATH
PATH=$PATH:$HOME/.local/bin:$HOME/bin
PATH=$PATH:/its1/GB_BT2/jianzuoyi/biosoft/smrt_bin
export PATH

# User specific environment and startup programs
alias ll=' ls -lh'
alias e='emacsclient -t -a ""'
alias grep='grep -E --color=auto'

# do not show hidden files in the list
set match-hidden-files off
 
# auto complete ignoring case
set show-all-if-ambiguous on
set completion-ignore-case on
